ISED-Design-CoE/ISED-Design-CoE.github.io

NCLL/review.html
The button is placed right next to the save button, at least for now.
=> Add print button

NCLL/select-licensee.html, NCLL/tech-details.html
Not sure if I used wet correctly.
Also, any button can be pressed to go to the dashboard, and there is no validation.
=> Change licensee to radio button

NCLL/licence-area.html
Right now these are very simple. 
I am not really good at writing instructions, and since I am familiar with leaflet, interaction with the map is second nature to me
=> First draft of map instructions

NCLL/licence-area.html
We should definitely not update the main branch during testing, but since this is a feature, not sure if we want to add it between sessions.
=> save shape on calculate

NCLL/licence-area.html
- shows when there is something on the map
- updates while drawing and editing
=> add area textbox on the map

NCLL/filter-rows.js, NCLL/licences.html
1. Currently the "Reset Filter" options removes the url params. Since the url param is a filter checkbox, this makes more sense to me.
2. Payment due is a status, but does not show up on the status column, or anywhere else. I believe it should be readable on the rows, but I am not sure if status is the right place for it.
=> Fix filter

NCLL/applications.html, NCLL/filter-rows.js, NCLL/licences.html
commit also prevents rows from having multiple status
I store the status in an attribute called "status".
I said that I would complete this after doing the minimum cost, but since the minimum costs also requires implementing the calculation of cost per month for temp licences, it is taking more time then expected.
=> replace class with status attribute

NCLL/general.html, NCLL/licence-area.html, NCLL/review.html
This is a fairly large PR. I don't know if it is necessary for the testing next week.
I tried to test it a bit, but I would imagine that there is a number of bugs right now.
=> Minimum price

NCLL/get_wkt.html
This commit removes a lot of code that is not used in this tool.
=> Fix bugs and add features from meeting

NCLL/A/application-side-filter.html, NCLL/A/application-status-checkbox.html, NCLL/A/filter-rows.js
This modernizes and implement the following branches: ``filter-by-checkbox`` and ``filter-by-height-and-actions-width``
=> PR to modernize and implement old branches

NCLL/A/index.html, NCLL/index.html
Before, you were not able to select your band
=> Fix apply from SMS

SAWI/auction-table.html, SAWI/filter-rows.js
sorry for the messy diffs, havent had a change to set up my git correctly yet.
=> remove id from tables

SAWI/auction-landing-page.html, SAWI/populate-whats-new.js
For the auction-landing-page.html most of it is automatic changes by [prettier](https://prettier.io/)
=> add json elements in what's new

SAWI/3800mhz.html
Minor updates to the content of the first tab on the 3800MHz page. Added the table of key dates table and prefiltered the documents table.
=> Finished tabbed auctions page

SAWI/Millimetre-scroll.html
Created the scroll page for millimetre wave
=> Created the scroll page for millimetre wave

SAWI/Millimetre.html
Millimetre wave tabbed interface created
=> Millimetre wave tabbed interface created

SAWI/auction-landing-page.html, SAWI/learn.html
Minor fixes to the links on the landing page and removed an extra <"main"> tag from the learn.html file
=> Minor fixes

SAWI/3800-scroll2.html, SAWI/millimetre-scroll2.html
Added 2 new auction pages with the document tables integrated on the page and added the links to the documents table.
=> Added 2 new auction pages with the document tables integrated

SAWI/README.md
This what I talked about during our meeting this morning.
chore → code that isnt a feature or a bugfix
=> fix python instructions

SAWI/scripts/i18n.js
Modified the javascript so that each link gets the lang from the referrer page
=> Modified the javascript 

SAWI/about-auctions.html, SAWI/auction-pages/auction-2018.html, SAWI/auction-pages/auction-2024.html, SAWI/auction-pages/auction-3500.html, SAWI/auction-pages/auction-3800.html, SAWI/auction-pages/auction-600.html, SAWI/auction-pages/auction-brs-applicants.html, SAWI/auction-pages/auction-brs.html, SAWI/auction-pages/auction-millimetrewave.html, SAWI/auction-table.html, SAWI/scrape/text.json
Completed porting the applicants page. Made some modifications to the other page so that the prettier extension works on them,
=> Completed porting the applicants page. 

broadcast-certificate-renewal/review.html, broadcast-certificate-renewal/success.html, broadcast-certificate-renewal/tables/certificate-table-review.html, broadcast-certificate-renewal/tables/sc6-table-review.html
I'm not sure if we really want this, but it's in the BRD, and we're supposed to be done / almost done with this.
And yeah, it's not very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
=> Fix review pages

broadcast-certificate-renewal/review.html, broadcast-certificate-renewal/success.html
Adds "John Doe" to the signature in the review and confirmation page.
=> Add signature in review and confirmation page.

broadcast-certificate-renewal/edit-contact.html, broadcast-certificate-renewal/index.html, broadcast-certificate-renewal/review.html, broadcast-certificate-renewal/success.html, broadcast-certificate-renewal/tables/sc6-table-review.html, broadcast-certificate-renewal/tables/sc6-table.html
1. remove validate when user has validated or continued from the edit state
2. show warning if at least 1 sc6 power level is over 100
3. change success message to the one in the flow
=> Feature meeting oct 10
